"""initial schema

Revision ID: e909d56fd80f
Revises: 
Create Date: 2026-09-30 12:58:29.021650
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'e909d56fd80f'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_templates',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('monitor_key', sa.String(length=60), nullable=False),
    sa.Column('resource_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('definition', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_templates')),
    sa.UniqueConstraint('key', name=op.f('uq_dashboard_templates_key'))
    )
    op.create_index(op.f('ix_dashboard_templates_monitor_key'), 'dashboard_templates', ['monitor_key'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('entra_tenant_id', sa.String(length=64), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('entra_tenant_id', name=op.f('uq_organizations_entra_tenant_id')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_table('roles',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permissions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_roles'))
    )
    op.create_table('health_thresholds',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('monitor_key', sa.String(length=60), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('warning_threshold', sa.Float(), nullable=True),
    sa.Column('critical_threshold', sa.Float(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_health_thresholds_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_thresholds')),
    sa.UniqueConstraint('organization_id', 'monitor_key', 'metric_name', name='uq_health_thresholds_rule')
    )
    op.create_index(op.f('ix_health_thresholds_organization_id'), 'health_thresholds', ['organization_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('secret_ref', sa.String(length=200), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_notification_channels_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_index(op.f('ix_notification_channels_deleted_at'), 'notification_channels', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notification_channels_organization_id'), 'notification_channels', ['organization_id'], unique=False)
    op.create_table('projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tag_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_projects_org_slug')
    )
    op.create_index(op.f('ix_projects_deleted_at'), 'projects', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('entra_object_id', sa.String(length=64), nullable=False),
    sa.Column('entra_tenant_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('role_key', sa.String(length=50), nullable=False),
    sa.Column('role_managed_by_entra', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.ForeignKeyConstraint(['role_key'], ['roles.key'], name=op.f('fk_users_role_key_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('organization_id', 'entra_object_id', name='uq_users_org_oid')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_entra_object_id'), 'users', ['entra_object_id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=320), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=800), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_org_created', 'audit_logs', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('environments',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('tag_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_environments_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_environments_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_environments_project_slug')
    )
    op.create_index(op.f('ix_environments_deleted_at'), 'environments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_environments_organization_id'), 'environments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_environments_project_id'), 'environments', ['project_id'], unique=False)
    op.create_table('azure_connections',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('auth_method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('default_project_id', sa.Uuid(), nullable=True),
    sa.Column('default_environment_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_azure_connections_created_by_id_users')),
    sa.ForeignKeyConstraint(['default_environment_id'], ['environments.id'], name=op.f('fk_azure_connections_default_environment_id_environments')),
    sa.ForeignKeyConstraint(['default_project_id'], ['projects.id'], name=op.f('fk_azure_connections_default_project_id_projects')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_azure_connections_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_azure_connections'))
    )
    op.create_index(op.f('ix_azure_connections_deleted_at'), 'azure_connections', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_azure_connections_organization_id'), 'azure_connections', ['organization_id'], unique=False)
    op.create_index(op.f('ix_azure_connections_status'), 'azure_connections', ['status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('resource_count', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['azure_connections.id'], name=op.f('fk_subscriptions_connection_id_azure_connections')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_subscriptions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('organization_id', 'subscription_id', name='uq_subscriptions_org_sub')
    )
    op.create_index(op.f('ix_subscriptions_connection_id'), 'subscriptions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_deleted_at'), 'subscriptions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('sync_runs',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('trigger', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('steps', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['azure_connections.id'], name=op.f('fk_sync_runs_connection_id_azure_connections')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sync_runs_organization_id_organizations')),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_sync_runs_requested_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_runs'))
    )
    op.create_index(op.f('ix_sync_runs_connection_id'), 'sync_runs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_organization_id'), 'sync_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sync_runs_status'), 'sync_runs', ['status'], unique=False)
    op.create_table('resource_groups',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_ref_id', sa.Uuid(), nullable=False),
    sa.Column('azure_id', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_resource_groups_organization_id_organizations')),
    sa.ForeignKeyConstraint(['subscription_ref_id'], ['subscriptions.id'], name=op.f('fk_resource_groups_subscription_ref_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resource_groups')),
    sa.UniqueConstraint('organization_id', 'azure_id', name='uq_resource_groups_org_azure_id')
    )
    op.create_index(op.f('ix_resource_groups_deleted_at'), 'resource_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resource_groups_organization_id'), 'resource_groups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_resource_groups_subscription_ref_id'), 'resource_groups', ['subscription_ref_id'], unique=False)
    op.create_table('resources',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_ref_id', sa.Uuid(), nullable=False),
    sa.Column('resource_group_id', sa.Uuid(), nullable=True),
    sa.Column('azure_id', sa.String(length=800), nullable=False),
    sa.Column('name', sa.String(length=260), nullable=False),
    sa.Column('resource_type', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=60), nullable=True),
    sa.Column('subscription_id', sa.String(length=64), nullable=False),
    sa.Column('resource_group', sa.String(length=200), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('properties', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('monitor_key', sa.String(length=60), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_source', sa.String(length=30), nullable=False),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('health_reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('health_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('azure_availability_state', sa.String(length=30), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['azure_connections.id'], name=op.f('fk_resources_connection_id_azure_connections')),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_resources_environment_id_environments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_resources_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_resources_project_id_projects')),
    sa.ForeignKeyConstraint(['resource_group_id'], ['resource_groups.id'], name=op.f('fk_resources_resource_group_id_resource_groups')),
    sa.ForeignKeyConstraint(['subscription_ref_id'], ['subscriptions.id'], name=op.f('fk_resources_subscription_ref_id_subscriptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources')),
    sa.UniqueConstraint('organization_id', 'azure_id', name='uq_resources_org_azure_id')
    )
    op.create_index(op.f('ix_resources_connection_id'), 'resources', ['connection_id'], unique=False)
    op.create_index(op.f('ix_resources_deleted_at'), 'resources', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_resources_health_status'), 'resources', ['health_status'], unique=False)
    op.create_index(op.f('ix_resources_location'), 'resources', ['location'], unique=False)
    op.create_index(op.f('ix_resources_monitor_key'), 'resources', ['monitor_key'], unique=False)
    op.create_index(op.f('ix_resources_name'), 'resources', ['name'], unique=False)
    op.create_index('ix_resources_org_type', 'resources', ['organization_id', 'resource_type'], unique=False)
    op.create_index(op.f('ix_resources_organization_id'), 'resources', ['organization_id'], unique=False)
    op.create_index('ix_resources_project_env', 'resources', ['project_id', 'environment_id'], unique=False)
    op.create_index(op.f('ix_resources_resource_group'), 'resources', ['resource_group'], unique=False)
    op.create_index(op.f('ix_resources_resource_group_id'), 'resources', ['resource_group_id'], unique=False)
    op.create_index(op.f('ix_resources_subscription_id'), 'resources', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_resources_subscription_ref_id'), 'resources', ['subscription_ref_id'], unique=False)
    op.create_table('alert_rules',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('monitor_key', sa.String(length=60), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('environment_id', sa.Uuid(), nullable=True),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('operator', sa.String(length=5), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('window_minutes', sa.Integer(), nullable=False),
    sa.Column('notification_channel_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_alert_rules_created_by_id_users')),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_alert_rules_environment_id_environments')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_alert_rules_organization_id_organizations')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_alert_rules_project_id_projects')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_alert_rules_resource_id_resources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_index(op.f('ix_alert_rules_deleted_at'), 'alert_rules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_alert_rules_organization_id'), 'alert_rules', ['organization_id'], unique=False)
    op.create_table('dashboards',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('is_customized', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_dashboards_created_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dashboards_organization_id_organizations')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_dashboards_resource_id_resources')),
    sa.ForeignKeyConstraint(['template_id'], ['dashboard_templates.id'], name=op.f('fk_dashboards_template_id_dashboard_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboards')),
    sa.UniqueConstraint('organization_id', 'resource_id', name='uq_dashboards_org_resource')
    )
    op.create_index(op.f('ix_dashboards_deleted_at'), 'dashboards', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dashboards_organization_id'), 'dashboards', ['organization_id'], unique=False)
    op.create_table('alerts',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('operator', sa.String(length=5), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], name=op.f('fk_alerts_acknowledged_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_alerts_organization_id_organizations')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_alerts_resource_id_resources')),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], name=op.f('fk_alerts_rule_id_alert_rules')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index('ix_alerts_fingerprint', 'alerts', ['organization_id', 'fingerprint'], unique=False)
    op.create_index('ix_alerts_org_status', 'alerts', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_organization_id'), 'alerts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_alerts_resource_id'), 'alerts', ['resource_id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=100), nullable=False),
    sa.Column('widget_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], name=op.f('fk_dashboard_widgets_dashboard_id_dashboards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dashboard_widgets'))
    )
    op.create_index(op.f('ix_dashboard_widgets_dashboard_id'), 'dashboard_widgets', ['dashboard_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('alert_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_alert_events_actor_user_id_users')),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], name=op.f('fk_alert_events_alert_id_alerts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_events'))
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    # ### end Alembic commands ###

    # Seed application roles. Permissions are enforced from app.core.permissions at runtime;
    # these rows record the definitions for reporting and satisfy users.role_key.
    roles = sa.table(
        "roles",
        sa.column("key", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.Text),
        sa.column("permissions", sa.JSON),
        sa.column("is_system", sa.Boolean),
    )
    op.bulk_insert(roles, [
        {"key": "super_admin", "name": "Super Admin", "is_system": True,
         "description": "Full control, including user and platform settings.",
         "permissions": ["*"]},
        {"key": "admin", "name": "Admin", "is_system": True,
         "description": "Manage projects, Azure connections, dashboards and alert rules.",
         "permissions": ["dashboards:view", "dashboards:manage", "resources:view", "logs:view", "logs:run_kql",
                         "azure:connect", "azure:sync", "projects:manage", "alerts:view", "alerts:manage",
                         "alerts:acknowledge", "audit:view"]},
        {"key": "operator", "name": "Operator", "is_system": True,
         "description": "View everything, run log queries, acknowledge alerts and trigger syncs.",
         "permissions": ["dashboards:view", "resources:view", "logs:view", "logs:run_kql", "azure:sync",
                         "alerts:view", "alerts:acknowledge"]},
        {"key": "viewer", "name": "Viewer", "is_system": True,
         "description": "Read-only access to dashboards, resources and alerts.",
         "permissions": ["dashboards:view", "resources:view", "alerts:view"]},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_dashboard_widgets_dashboard_id'), table_name='dashboard_widgets')
    op.drop_table('dashboard_widgets')
    op.drop_index(op.f('ix_alerts_resource_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_organization_id'), table_name='alerts')
    op.drop_index('ix_alerts_org_status', table_name='alerts')
    op.drop_index('ix_alerts_fingerprint', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_dashboards_organization_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_deleted_at'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_alert_rules_organization_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_deleted_at'), table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index(op.f('ix_resources_subscription_ref_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_subscription_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_group_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_group'), table_name='resources')
    op.drop_index('ix_resources_project_env', table_name='resources')
    op.drop_index(op.f('ix_resources_organization_id'), table_name='resources')
    op.drop_index('ix_resources_org_type', table_name='resources')
    op.drop_index(op.f('ix_resources_name'), table_name='resources')
    op.drop_index(op.f('ix_resources_monitor_key'), table_name='resources')
    op.drop_index(op.f('ix_resources_location'), table_name='resources')
    op.drop_index(op.f('ix_resources_health_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_deleted_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_connection_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_resource_groups_subscription_ref_id'), table_name='resource_groups')
    op.drop_index(op.f('ix_resource_groups_organization_id'), table_name='resource_groups')
    op.drop_index(op.f('ix_resource_groups_deleted_at'), table_name='resource_groups')
    op.drop_table('resource_groups')
    op.drop_index(op.f('ix_sync_runs_status'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_organization_id'), table_name='sync_runs')
    op.drop_index(op.f('ix_sync_runs_connection_id'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_deleted_at'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_connection_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_azure_connections_status'), table_name='azure_connections')
    op.drop_index(op.f('ix_azure_connections_organization_id'), table_name='azure_connections')
    op.drop_index(op.f('ix_azure_connections_deleted_at'), table_name='azure_connections')
    op.drop_table('azure_connections')
    op.drop_index(op.f('ix_environments_project_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_organization_id'), table_name='environments')
    op.drop_index(op.f('ix_environments_deleted_at'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_org_created', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_entra_object_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_deleted_at'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notification_channels_organization_id'), table_name='notification_channels')
    op.drop_index(op.f('ix_notification_channels_deleted_at'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_health_thresholds_organization_id'), table_name='health_thresholds')
    op.drop_table('health_thresholds')
    op.drop_table('roles')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_dashboard_templates_monitor_key'), table_name='dashboard_templates')
    op.drop_table('dashboard_templates')
    # ### end Alembic commands ###
