#!/usr/bin/env bash
# Creates (or updates) the single Microsoft Entra app registration used by the Monitoring Platform
# for both the website sign-in (SPA, PKCE) and the API (scope access_as_user), then prints a complete
# .env for docker-compose.
#
# Requirements: Azure CLI signed in to the target tenant as a user who may register applications
# (Entra role "Application Developer", "Cloud Application Administrator" or higher). Azure Cloud Shell works.
#
#   SUPER_ADMIN_UPN=first.admin@company.com APP_URL=https://monitoring.company.com \
#     bash scripts/create-entra-app.sh > monitoring.env
#
# Safe to re-run: an existing registration with the same display name is updated, not duplicated.
# No client secret is created: the SPA uses PKCE and the API only validates tokens.
set -euo pipefail

APP_NAME="${APP_NAME:-Affinia Monitoring Platform}"
APP_URL="${APP_URL:-https://monitoring.affinia.co.uk}"
APP_URL="${APP_URL%/}"

log() { echo "$*" >&2; }
new_uuid() {
  uuidgen 2>/dev/null || cat /proc/sys/kernel/random/uuid 2>/dev/null ||
    python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null || python -c "import uuid; print(uuid.uuid4())"
}

TENANT_ID="$(az account show --query tenantId -o tsv)"
log "Tenant: ${TENANT_ID}"

if [ -n "${SUPER_ADMIN_UPN:-}" ]; then
  ADMIN_OID="$(az ad user show --id "${SUPER_ADMIN_UPN}" --query id -o tsv)"
else
  SUPER_ADMIN_UPN="$(az ad signed-in-user show --query userPrincipalName -o tsv)"
  ADMIN_OID="$(az ad signed-in-user show --query id -o tsv)"
fi
log "First Super Admin: ${SUPER_ADMIN_UPN}"

APP_ID="$(az ad app list --display-name "${APP_NAME}" --query "[0].appId" -o tsv)"
if [ -z "${APP_ID}" ]; then
  APP_ID="$(az ad app create --display-name "${APP_NAME}" --sign-in-audience AzureADMyOrg --query appId -o tsv)"
  log "Created app registration ${APP_ID}"
else
  log "Updating existing app registration ${APP_ID}"
fi
APP_OBJECT_ID="$(az ad app show --id "${APP_ID}" --query id -o tsv)"

az ad app update --id "${APP_ID}" --identifier-uris "api://${APP_ID}"

SCOPE_ID="$(az ad app show --id "${APP_ID}" --query "api.oauth2PermissionScopes[?value=='access_as_user'].id | [0]" -o tsv)"
[ -n "${SCOPE_ID}" ] || SCOPE_ID="$(new_uuid)"

GRAPH="https://graph.microsoft.com/v1.0/applications/${APP_OBJECT_ID}"

# v2 access tokens (the API accepts only v2 issuers), the delegated scope, and the SPA redirect URI.
az rest --method PATCH --uri "${GRAPH}" --headers "Content-Type=application/json" --body "{
  \"api\": {
    \"requestedAccessTokenVersion\": 2,
    \"oauth2PermissionScopes\": [{
      \"id\": \"${SCOPE_ID}\",
      \"value\": \"access_as_user\",
      \"type\": \"User\",
      \"isEnabled\": true,
      \"adminConsentDisplayName\": \"Access the Monitoring Platform\",
      \"adminConsentDescription\": \"Allows the Monitoring Platform website to call its API as the signed-in user.\",
      \"userConsentDisplayName\": \"Access the Monitoring Platform\",
      \"userConsentDescription\": \"Allows the Monitoring Platform website to call its API on your behalf.\"
    }]
  },
  \"spa\": { \"redirectUris\": [\"${APP_URL}\"] }
}"

# The website is the same app as the API: pre-authorise it so users are never asked to consent.
az rest --method PATCH --uri "${GRAPH}" --headers "Content-Type=application/json" --body "{
  \"api\": { \"preAuthorizedApplications\": [{ \"appId\": \"${APP_ID}\", \"delegatedPermissionIds\": [\"${SCOPE_ID}\"] }] }
}"

az ad sp show --id "${APP_ID}" >/dev/null 2>&1 || az ad sp create --id "${APP_ID}" >/dev/null
log "App registration ready. Paste the output below into the server's .env, then: docker-compose up -d --build"

cat <<ENV
# Azure Monitoring Platform - server configuration (generated by scripts/create-entra-app.sh)
# Identifiers only: nothing in this file is a secret, but keep it out of source control.

# ---------------------------------------------------------------- General
# development is required while AZURE_PROVIDER=mock. Switch both when real Azure access is set up.
ENVIRONMENT=development
APP_NAME=Azure Monitoring Platform
LOG_LEVEL=INFO

# ---------------------------------------------------------------- Database / Redis
# docker-compose points the containers at its own postgres and redis services; these are for host runs.
DATABASE_URL=postgresql+asyncpg://monitoring:monitoring@localhost:5432/monitoring
DATABASE_ECHO=false
REDIS_URL=redis://localhost:6379/0
# Only applies when the database volume is first created (URL-safe characters only).
# POSTGRES_PASSWORD=

# ---------------------------------------------------------------- Authentication (Microsoft Entra SSO)
AUTH_MODE=entra
ENTRA_TENANT_ID=${TENANT_ID}
ENTRA_CLIENT_ID=${APP_ID}
ENTRA_AUDIENCE=api://${APP_ID}
ENTRA_REQUIRED_SCOPE=access_as_user
ENTRA_AUTHORITY_HOST=https://login.microsoftonline.com
# First Super Admin (${SUPER_ADMIN_UPN}). Ignored once an active Super Admin exists.
BOOTSTRAP_SUPER_ADMIN_OIDS=${ADMIN_OID}

# ---------------------------------------------------------------- Azure access
AZURE_PROVIDER=mock
# AZURE_TENANT_ID=${TENANT_ID}
# AZURE_CLIENT_ID=
# KEY_VAULT_URL=

# ---------------------------------------------------------------- Resource mapping
PROJECT_TAG_KEYS=project,Project,application
ENVIRONMENT_TAG_KEYS=environment,Environment,env

# ---------------------------------------------------------------- Background jobs
TASK_BACKEND=celery
SYNC_INTERVAL_MINUTES=15
HEALTH_INTERVAL_MINUTES=5

# ---------------------------------------------------------------- Caching (seconds)
CACHE_TTL_METRICS=60
CACHE_TTL_RESOURCE_GRAPH=300
CACHE_TTL_HEALTH=120

# ---------------------------------------------------------------- HTTP
CORS_ORIGINS=${APP_URL}
RATE_LIMIT_PER_MINUTE=300
RATE_LIMIT_KQL_PER_MINUTE=30
RATE_LIMIT_AUTH_FAILURES_PER_MINUTE=30
LOG_QUERY_MAX_ROWS=5000
# HTTPS reverse proxy + the frontend nginx container in front of the API.
PROXY_HOPS=2

# ---------------------------------------------------------------- docker-compose
# Published web port. Use WEB_BIND=127.0.0.1 if only the host reverse proxy should reach it.
WEB_BIND=0.0.0.0
WEB_PORT=8080

# ---------------------------------------------------------------- Frontend (compiled into the browser bundle)
VITE_API_BASE_URL=/api/v1
VITE_AUTH_MODE=entra
VITE_ENTRA_CLIENT_ID=${APP_ID}
VITE_ENTRA_TENANT_ID=${TENANT_ID}
VITE_ENTRA_API_SCOPE=api://${APP_ID}/access_as_user
VITE_ENTRA_REDIRECT_URI=${APP_URL}
ENV
